#!/bin/sh

usage(){
	fmt <<EOF
DESCRIPTION
	Display the IP address of this host as seen from the public internet.
	
USAGE
	external-ip
EOF
	exit
}
if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
#End boilerplate

dig +short myip.opendns.com @resolver1.opendns.com
