#!/bin/bash

usage(){
	echo -n
	fmt <<EOF
DESCRIPTION
	Display the gateway (typically the router) address of the current network.
	
USAGE
	gateway
EOF
	exit
}
if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
#End boilerplate

while read -r line; do
	flagsColumn=$(echo "$line" | tr -s ' '| cut -d ' ' -f 4)
	
	if [ "$flagsColumn" != "Flags" -a "$flagsColumn" != "table" ]; then
		flags=$(echo "$flagsColumn" | egrep "G")
		if [ "$flags" != "" ]; then
			address=$(echo "$line" | tr -s ' '| cut -d ' ' -f 2)
			echo "http://$address"
		fi
	fi
done <<< "$(route)"
