#!/bin/sh

usage(){
	fmt <<EOF
DESCRIPTION
	Display the gateway (typically the router) address of the current network.
	
USAGE
	gateway
		Print the gateway address to standard output.
		
	gateway -o,--open
		Open the gateway address in the default web browser.
EOF
	exit
}
if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
#End boilerplate

route | while read -r line; do
	flagsColumn=$(echo "${line}" | tr -s ' '| cut -d ' ' -f 4)
	
	if [ "${flagsColumn}" != "Flags" -a "${flagsColumn}" != "table" ]; then
		flags=$(echo "${flagsColumn}" | egrep "G")
		if [ "${flags}" != "" ]; then
			address=$(echo "${line}" | tr -s ' '| cut -d ' ' -f 2)
			
			if [ $# -eq 0 ]; then
				echo "http://${address}"
			elif [ "$1" = "-o" -o "$1" = "--open" ]; then
				xdg-open "http://${address}"
			fi
		fi
	fi
done
