#!/bin/bash

usage(){
	echo -n
	fmt <<EOF
DESCRIPTION
	Remove old kernel versions from the system.
	
USAGE
	remove-old-kernels
		Remove old kernels without confirmation.
		
	remove-old-kernels -d,--dry-run
		Simulate removing old kernels, but do not take action.
EOF
	exit
}
die(){ echo -e "Error: ${1:-"Unknown error at line $LINENO."}" 1>&2; exit 1; }
require(){ command -v $1 > /dev/null 2>&1 || { suggestion=""; if [ ! -z "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.$suggestion"; } }
if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
#End boilerplate

if [ $# -eq 0 ]; then
	dpkg -l "linux-*" | awk '/^ii/{ print $2}' | grep -v -e `uname -r | cut -f1,2 -d"-"` | grep -e "[0-9]" | xargs sudo apt-get -y remove
elif [ "$1" = "-d" -o "$1" = "--dry-run" ]; then
	dpkg -l "linux-*" | awk '/^ii/{ print $2}' | grep -v -e `uname -r | cut -f1,2 -d"-"` | grep -e "[0-9]" | xargs sudo apt-get --dry-run remove
fi
