#!/bin/bash

brightness=0

usage(){
	echo -n
	fmt <<EOF
DESCRIPTION
	Set the laptop screen brightness level.
	
USAGE
	set-brightness [0-15]
		The brightness level defaults to $brightness.
EOF
	exit
}
if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
#End boilerplate


if [ $# -ne 0 ]; then
	brightness="$1"
fi

if [[ "$brightness" =~ ^[0-9]+$ ]]; then
	echo -e "$brightness" | sudo tee /sys/class/backlight/acpi_video0/brightness > /dev/null
else
	die "Expecting a number."
fi


