#!/bin/zsh

usage(){
	echo -n
	fmt <<EOF
DESCRIPTION
	Open or resume an SSH connection using GNOME Terminal and MOSH.
	
USAGE
	super-ssh USER@HOSTNAME
EOF
	exit
}
if [ $# -eq 1 ]; then if [ "$1" = "--help" -o "$1" = "-h" ]; then usage; fi fi
#End boilerplate

if [ $# -eq 0 ]; then
	usage
fi

profile=`echo "$1" | cut -d"@" -f2-2`

gnome-terminal --disable-factory --title="$profile" --window-with-profile="$profile" -x zsh -c "mosh $1 -- zsh -c \"tmux a\""
